import 'package:flutter/material.dart';import 'package:newsapp/model.dart';
void main()=>runApp(MaterialApp(home: NewsApp(),debugShowCheckedModeBanner: false,));

class NewsApp extends StatelessWidget {
  @override Widget build(BuildContext context){return Scaffold(body: Stack(fit: StackFit.expand,children: <Widget>[GradientContainer(),ListView(physics: BouncingScrollPhysics(),padding: EdgeInsets.all(20.0),children: <Widget>[Divider(height: 80.0),Row(children: <Widget>[DesignedContainer("Business","https://newsapi.org/v2/top-headlines?country=in&category=business&apiKey=3fc464c420834d6fb76899f176e1ae6d","asset/business.png"),Container(width: 20.0,),DesignedContainer("Sports","https://newsapi.org/v2/top-headlines?country=in&category=sports&apiKey=3fc464c420834d6fb76899f176e1ae6d","asset/sports.png")],),Divider(height: 50.0,),Row(children: <Widget>[DesignedContainer("Science","https://newsapi.org/v2/top-headlines?country=in&category=science&apiKey=3fc464c420834d6fb76899f176e1ae6d","asset/science.png"),Container(width: 20.0,),DesignedContainer("Technology","https://newsapi.org/v2/top-headlines?country=in&category=technology&apiKey=3fc464c420834d6fb76899f176e1ae6d","asset/technology.png")],),Divider(height: 50.0,),Row(children: <Widget>[DesignedContainer("Health","https://newsapi.org/v2/top-headlines?country=in&category=health&apiKey=3fc464c420834d6fb76899f176e1ae6d","asset/health.png"),Container(width: 20.0,),DesignedContainer("Entertainment","https://newsapi.org/v2/top-headlines?country=in&category=entertainment&apiKey=3fc464c420834d6fb76899f176e1ae6d","asset/entertainment.png")],),],)],),);}}

class DesignedContainer extends StatelessWidget{String text;String url;String pic;DesignedContainer(this.text,this.url,this.pic);
  @override Widget build(BuildContext context) {return GestureDetector(child: Container(child: Center(child: ListView(physics: BouncingScrollPhysics(),padding: EdgeInsets.all(5.0),children: <Widget>[Image.asset(this.pic,),Divider(),Text(this.text,textAlign: TextAlign.center,style: TextStyle(color: Colors.white,fontSize: 20.0))],)),margin: EdgeInsets.all(10.0),constraints:BoxConstraints(maxHeight: 130.0,minHeight: 120.0,maxWidth: 130.0,minWidth: 130.0),decoration: BoxDecoration(border: Border.all(width: 1,color: Colors.transparent),borderRadius: BorderRadius.all(Radius.circular(15.0),)),),onTap: (){Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context)=>ModelNews(this.url)));},);}}

class GradientContainer extends StatelessWidget {
  @override Widget build(BuildContext context) {return Container(decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment.topLeft,end: Alignment.bottomRight,stops: [0.1,0.3,0.7,0.9],colors: [Colors.blueGrey[900],Colors.blueGrey[800],Colors.blueGrey[700],Colors.blueGrey[600]])),);}}